# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:9090}

# Management settings
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: output.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: oauth2-client-server
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# Security settings
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8080/oauth2/user/info

# Mybatis settings
mybatis:
  type-aliases-package: com.incarcloud.oauth2client.pojo
  mapperLocations: classpath:mapper/**/*Mapper.xml
